import {
  coat1, coat2, coat3,
  blouse1, blouse2, blouse3,
  suit1, suit2, suit3,
  turtleneck1, turtleneck2, turtleneck3,
  trousers1, trousers2, trousers3,
  blazer1, blazer2, blazer3,
  skirt1, skirt2, skirt3,
  shirt1, shirt2, shirt3,
  dress1, dress2, dress3,
  chino1, chino2, chino3,
  bodysuit1, bodysuit2, bodysuit3,
  jacket1, jacket2, jacket3
} from "../assets/images";

export const imageMap = {
  coat1,
  coat2,
  coat3,
  blouse1,
  blouse2,
  blouse3,
  suit1,
  suit2,
  suit3,
  turtleneck1,
  turtleneck2,
  turtleneck3,
  trousers1,
  trousers2,
  trousers3,
  blazer1,
  blazer2,
  blazer3,
  skirt1,
  skirt2,
  skirt3,
  shirt1,
  shirt2,
  shirt3,
  dress1,
  dress2,
  dress3,
  chino1,
  chino2,
  chino3,
  bodysuit1,
  bodysuit2,
  bodysuit3,
  jacket1,
  jacket2,
  jacket3
};