import {
  coat1, coat2, coat3,
  blouse1, blouse2, blouse3,
  suit1, suit2, suit3,
  turtleneck1, turtleneck2, turtleneck3,
  trousers1, trousers2, trousers3,
  blazer1, blazer2, blazer3,
  skirt1, skirt2, skirt3,
  shirt1, shirt2, shirt3,
  dress1, dress2, dress3,
  chino1, chino2, chino3,
  bodysuit1, bodysuit2, bodysuit3,
  jacket1, jacket2, jacket3
} from "../assets/images";

export const products = [
  {
    id: 1,
    name: "Obsidian Wool Coat",
    category: "women",
    subcategory: "coats",
    price: 289,
    originalPrice: 380,
    discount: 24,
    rating: 4.8,
    reviews: 124,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#1a1a1a", "#4a3728", "#2c3e50"],
    colorNames: ["Obsidian", "Cognac", "Midnight Blue"],
    images: [
      coat1,
      coat2,
      coat3,
    ],
    description: "A structured wool-blend coat with clean lines and a timeless silhouette. Perfect for transitional weather, this coat features a hidden button closure, two side pockets, and a fully lined interior for ultimate comfort.",
    tags: ["new", "featured"],
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: 2,
    name: "Silk Drape Blouse",
    category: "women",
    subcategory: "tops",
    price: 145,
    originalPrice: 145,
    discount: 0,
    rating: 4.6,
    reviews: 89,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#f5f0e8", "#c4a882", "#8b7355"],
    colorNames: ["Ivory", "Sand", "Camel"],
    images: [
  blouse1,
  blouse2,
  blouse3,
],
    description: "Flowing 100% silk blouse with a draped neckline and relaxed fit. The fluid fabric moves beautifully and transitions effortlessly from day to evening wear.",
    tags: ["featured"],
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: 3,
    name: "Tailored Slim Suit",
    category: "men",
    subcategory: "suits",
    price: 420,
    originalPrice: 580,
    discount: 28,
    rating: 4.9,
    reviews: 203,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#1c1c1c", "#2f4f4f", "#1a237e"],
    colorNames: ["Charcoal", "Dark Teal", "Navy"],
    images: [
  suit1,
  suit2,
  suit3,
],
    description: "A masterfully tailored slim-fit suit crafted from premium wool-blend fabric. Features a two-button closure, notch lapels, and a modern slim cut that flatters every physique.",
    tags: ["sale", "featured"],
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: 4,
    name: "Merino Turtleneck",
    category: "men",
    subcategory: "knitwear",
    price: 165,
    originalPrice: 200,
    discount: 18,
    rating: 4.7,
    reviews: 156,
    sizes: ["S", "M", "L", "XL"],
    colors: ["#f5f5f0", "#8b7355", "#2c2c2c"],
    colorNames: ["Ivory", "Camel", "Graphite"],
    images: [
  turtleneck1,
  turtleneck2,
  turtleneck3,
],
    description: "Luxuriously soft 100% merino wool turtleneck with a ribbed finish. Naturally temperature-regulating and incredibly comfortable against the skin.",
    tags: ["new"],
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: 5,
    name: "Pleated Wide-Leg Trousers",
    category: "women",
    subcategory: "bottoms",
    price: 195,
    originalPrice: 260,
    discount: 25,
    rating: 4.5,
    reviews: 78,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#f5f0e8", "#2c2c2c", "#8b7355"],
    colorNames: ["Cream", "Black", "Tan"],
    images: [
  trousers1,
  trousers2,
  trousers3,
],
    description: "High-waisted pleated trousers with a wide leg silhouette. Crafted from premium crepe fabric that drapes elegantly and maintains its shape throughout the day.",
    tags: ["sale"],
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: 6,
    name: "Linen Relaxed Blazer",
    category: "men",
    subcategory: "jackets",
    price: 275,
    originalPrice: 275,
    discount: 0,
    rating: 4.6,
    reviews: 92,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#d4c5a9", "#2c2c2c", "#4a6741"],
    colorNames: ["Sand", "Black", "Forest"],
    images: [
  blazer1,
  blazer2,
  blazer3,
],
    description: "A relaxed-fit blazer crafted from 100% linen for breathable comfort. Features patch pockets, a notched lapel, and a slightly boxy cut for a modern, effortless look.",
    tags: ["new"],
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: 7,
    name: "Leather Mini Skirt",
    category: "women",
    subcategory: "bottoms",
    price: 220,
    originalPrice: 300,
    discount: 27,
    rating: 4.4,
    reviews: 61,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#1a1a1a", "#4a3728", "#8b2020"],
    colorNames: ["Black", "Cognac", "Bordeaux"],
    images: [
  skirt1,
  skirt2,
  skirt3,
],
    description: "A sleek mini skirt in premium lambskin leather. Features a high waist, subtle A-line cut, and invisible zip closure. An investment piece that elevates any outfit.",
    tags: ["sale", "new"],
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: 8,
    name: "Oxford Button-Down",
    category: "men",
    subcategory: "shirts",
    price: 115,
    originalPrice: 140,
    discount: 18,
    rating: 4.7,
    reviews: 187,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#f5f5f5", "#c8d8e8", "#2c2c2c"],
    colorNames: ["White", "Light Blue", "Black"],
    images: [
  shirt1,
  shirt2,
  shirt3,
],
    description: "A timeless Oxford button-down shirt crafted from premium 100% cotton. Features a classic fit, button-down collar, and a chest pocket. The cornerstone of any wardrobe.",
    tags: ["sale"],
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: 9,
    name: "Cashmere Wrap Dress",
    category: "women",
    subcategory: "dresses",
    price: 340,
    originalPrice: 420,
    discount: 19,
    rating: 4.9,
    reviews: 143,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#8b2020", "#2c3e50", "#1a1a1a"],
    colorNames: ["Ruby", "Midnight", "Black"],
    images: [
  dress1,
  dress2,
  dress3,
],
    description: "An elegant wrap dress in pure cashmere blend. The wrap silhouette flatters all body types while the luxurious fabric provides exceptional warmth and softness.",
    tags: ["featured", "sale"],
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: 10,
    name: "Slim Chino Trousers",
    category: "men",
    subcategory: "bottoms",
    price: 135,
    originalPrice: 135,
    discount: 0,
    rating: 4.5,
    reviews: 221,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#d4c5a9", "#2c2c2c", "#4a6741"],
    colorNames: ["Khaki", "Black", "Olive"],
    images: [
  chino1,
  chino2,
  chino3,
],
    description: "Slim-fit chino trousers crafted from stretch cotton blend for all-day comfort. Features a mid-rise waist, slim leg, and a clean finish — smart casual perfection.",
    tags: ["new"],
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: 11,
    name: "Knit Bodysuit",
    category: "women",
    subcategory: "tops",
    price: 98,
    originalPrice: 130,
    discount: 25,
    rating: 4.3,
    reviews: 55,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#f5f0e8", "#1a1a1a", "#8b2020"],
    colorNames: ["Cream", "Black", "Burgundy"],
    images: [
  bodysuit1,
  bodysuit2,
  bodysuit3,
],
    description: "A sleek ribbed knit bodysuit with a scoop neckline and snap closure. Pairs perfectly with high-waisted bottoms for a polished, put-together look.",
    tags: ["sale"],
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: 12,
    name: "Premium Denim Jacket",
    category: "men",
    subcategory: "jackets",
    price: 185,
    originalPrice: 240,
    discount: 23,
    rating: 4.6,
    reviews: 98,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#4a5568", "#2c2c2c", "#c8d8e8"],
    colorNames: ["Washed Blue", "Black", "Light Wash"],
    images: [
  jacket1,
  jacket2,
  jacket3,
],
    description: "A classic denim jacket reimagined in premium selvedge denim. Features contrast stitching, chest pockets, and a comfortable regular fit that only gets better with age.",
    tags: ["sale"],
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
];

export const getFeatured  = () => products.filter(p => p.isFeatured);
export const getNew       = () => products.filter(p => p.isNew);
export const getSale      = () => products.filter(p => p.discount > 0);
export const getByCategory = (cat) => products.filter(p => p.category === cat);
export const getById      = (id)  => products.find(p => p.id === Number(id));
export const getSimilar   = (id, cat) => products.filter(p => p.category === cat && p.id !== Number(id)).slice(0, 4);